# Configuración del Juego de Preguntas

# DIMENSIONES
VENTANA_ANCHO = 600
VENTANA_ALTO = 500
PADDING_FRAME = 20

# Tamaños de cajas de texto
ENTRY_ANCHO = 10  # Para números
ENTRY_JUGADOR_ANCHO = 30
TEXT_PREGUNTA_ALTO = 6
TEXT_PREGUNTA_ANCHO = 50
TEXT_LISTA_JUGADORES_ALTO = 8
TEXT_LISTA_JUGADORES_ANCHO = 40
TEXT_PREGUNTAS_PREVIAS_ALTO = 5
TEXT_PREGUNTAS_PREVIAS_ANCHO = 50
TEXT_PREGUNTA_JUEGO_ALTO = 8
TEXT_PREGUNTA_JUEGO_ANCHO = 50

# FUENTES
# Formato: (tipo, tamaño, estilo) donde estilo puede ser "normal", "bold", "italic"
FUENTE_TITULO_PRINCIPAL = ("Arial", 16, "bold")
FUENTE_TITULO_SECCION = ("Arial", 18, "bold")
FUENTE_TITULO_TURNO = ("Arial", 16, "bold")
FUENTE_TITULO_FIN = ("Arial", 20, "bold")
FUENTE_SUBTITULO = ("Arial", 13, "bold")
FUENTE_TEXTO_NORMAL = ("Arial", 12, "normal")
FUENTE_TEXTO_PEQUENO = ("Arial", 11, "normal")
FUENTE_TEXTO_MUY_PEQUENO = ("Arial", 10, "italic")
FUENTE_TEXTO_MINIMO = ("Arial", 9, "normal")
FUENTE_ENTRY = ("Arial", 14, "normal")
FUENTE_PREGUNTA = ("Arial", 12, "normal")
FUENTE_BOTON_GRANDE = ("Arial", 13, "normal")
FUENTE_BOTON_NORMAL = ("Arial", 12, "normal")
FUENTE_BOTON_PEQUENO = ("Arial", 11, "normal")

# COLORES
COLOR_BOTON_PRIMARIO = "#4CAF50"  # Verde
COLOR_BOTON_SECUNDARIO = "#2196F3"  # Azul
COLOR_BOTON_PELIGRO = "#f44336"  # Rojo
COLOR_BOTON_ACCION = "#FF5722"  # Naranja

COLOR_TEXTO_BLANCO = "white"
COLOR_TEXTO_PRIMARIO = "#2196F3"  # Azul
COLOR_TEXTO_ACENTO = "#FF5722"  # Naranja
COLOR_TEXTO_EXITO = "#4CAF50"  # Verde

COLOR_FONDO_PREGUNTA = "#FFF9C4"  # Amarillo claro

# ESPACIADO (padding en pixeles)
PAD_PEQUENO = 5
PAD_NORMAL = 10
PAD_GRANDE = 15
PAD_MUY_GRANDE = 20
PAD_EXTRA_GRANDE = 30

# TAMAÑO DE BOTONES
BOTON_PAD_X_GRANDE = 30
BOTON_PAD_Y_GRANDE = 12
BOTON_PAD_X_NORMAL = 20
BOTON_PAD_Y_NORMAL = 10
BOTON_PAD_X_PEQUENO = 15
BOTON_PAD_Y_PEQUENO = 8
